### ISSUE TITLE
Insert doesn't change status bar

### ISSUE THREAD

**Issue by mjkpolo** [vimpostor/vim-tpipeline#10]
Hello, I apologize if this is the wrong way to open a request I am a newb. I love the plugin!!

The problem is that running neovim, the insert operation does not change the status. However, if you rapidly press up or down or left or right then insert, it does change. I think this has to do with `let g:tpipeline_cursormoved = 1` because rapidly moving then insert works which makes me think the up, down, left, or right triggers `cursormoved` and allows for insert to be picked up whereas `i` does not.

I searched all day on reddit to find this cool plugin, because I saw it once and made a mental note to try it when I switched to tmux!

**Comment by vimpostor** [comment]
Hi thanks so much for your kind words about the plugin, it made my day! :)

As for your issue, this is absolutely the right place for this.

For a quick workaround you can put the following in your vim config:
```vim
set updatetime=300 "updatetime for CursorHold
set noswapfile "this is optional (updatetime also influences the rate of writing to the swapfile)
```
That way the `CursorHoldI` `autocmd` will trigger after 300ms instead of the default 4000ms and update the statusline faster after entering Insert mode.

However I think I might be able to fix this from the plugin side as well. There is an `InsertEnter` autocmd, however it is triggered just before entering insert mode.
For example `:autocmd InsertEnter * echo(mode())` will always show `n` (normal mode) instead of `i`.
I am able to workaroud this by deferring the actual call by a few milliseconds to pickup the mode change, but I will have to investigate this more carefully how to implement this in the cleanest way.

**Comment by vimpostor** [comment]
I have now fixed this from the plugin side, this should work out of the box now.
Regardless of that, I still recommend using `set updatetime=300`, because many other plugins use `CursorHold` extensively.
