### ISSUE TITLE
How to disable position in commandline

### ISSUE THREAD

**Issue by meijieru** [vimpostor/vim-tpipeline#15]
before
![image](https://user-images.githubusercontent.com/9511136/141427399-75a53c1d-df06-45aa-baf1-ff60acd4a7a4.png)
after
![image](https://user-images.githubusercontent.com/9511136/141427306-47f925af-e854-4a1e-8c6e-a5860f0becee.png)

Thanks for your great work first!
One minor issue here is the position indicator exists if enable this plugin.
Is there any way to disable it?

**Comment by vimpostor** [comment]
This is a weird ege case, where vim's default behaviour (`set ruler`) will only show the indicator, if no statusline is set (OR if `laststatus=0`, which is set by this plugin), which in this case causes the inconsistent behaviour between inside and outside of tmux.
I didn't catch this earlier, because I have `set noruler` in my config, so thanks for the report. :)
It is fixed now in the latest version.
