### ISSUE TITLE
There are two status lines in nvim, how to remove them

### ISSUE THREAD

**Issue by j2501987804** [vimpostor/vim-tpipeline#36]
### Describe the bug

os:mac
terminal:iterm2
tmux:oh-my-tmux
line:lualine
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/41771911/192184154-e2b66705-319d-461f-b000-a563445cea8c.png">

tmux line
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/41771911/192184233-aabf07eb-43d3-49b7-9ce5-f4eb7f838aa2.png">

**Comment by vimpostor** [comment]
Usually it is done with `set laststatus=0`, but this plugin already does this by default.

In order to reproduce, I need more info. Can you provide your config file?

**Comment by vimpostor** [comment]
Why did you close this? Did you solve the issue?

**Comment by WilliamHsieh** [comment]
> Usually it is done with `set laststatus=0`, but this plugin already does this by default.

I'm actually facing a similar issue. Is there a way to keep using the global status line (laststatus=3) while keeping only one status line?

Because from what I've tested, laststatus=3 is showing duplicated status line.
The plugin is trying to get rid of the duplicated status line by setting laststatus=0, but in this way, a second status line will be shown in the split window, which is not what I want either.

**Comment by vimpostor** [comment]
> > Usually it is done with `set laststatus=0`, but this plugin already does this by default.
> 
> I'm actually facing a similar issue. Is there a way to keep using the global status line (laststatus=3) while keeping only one status line?

This issue was already discussed in #19

1. There is no other way to hide vim's own status line than to use `laststatus=0`. This is set automatically by this plugin, so there is no need for you to set this variable yourself.
2. The problem you are seeing is secondary statuslines as a sideeffect from vim's split statusline. It is correct, that `laststatus=3` will get rid of those split statuslines, but that will again cause vim's own main statusline to be visible (so we need to find a solution that works with `laststatus=0`)

The solution to this problem is described in `:h g:tpipeline_clearstl` and additionally you might need to set the `fillchars` option as detailed in https://github.com/vimpostor/vim-tpipeline/issues/19#issuecomment-1000844167

Let me know if you have any problems or artifacts with that solution.
Since vim doesn't support this without hacks, we might need to find another workaround or do an official upstream vim patch (wouldn't be the first time to get this plugin working without issues)

**Comment by WilliamHsieh** [comment]
> The solution to this problem is described in :h g:tpipeline_clearstl and additionally you might need to set the fillchars option as detailed in https://github.com/vimpostor/vim-tpipeline/issues/19#issuecomment-1000844167

When or how should I set this option? If I set the option before the plugin loads, both the split status line and the embedded part of the status line disappeared. However, if I set it after the plugin loads, the option doesn't seem to have any effects. 

And for the `set stl=%#StatusLine#` option, both the split status line and the embedded part of the status line also disappeared.

**Comment by vimpostor** [comment]
> When or how should I set this option? If I set the option before the plugin loads, both the split status line and the embedded part of the status line disappeared. However, if I set it after the plugin loads, the option doesn't seem to have any effects.

Looks like there was a regression, sorry about that.
It should work again now, the `g:tpipeline_clearstl` option needs to be set before the plugin is loaded.

**Comment by WilliamHsieh** [comment]
It works, mostly. However, the embedded part is no longer responsive. For example, `set stl=something` will change the split statusline to `something` but not the embedded part, whereas previously without the option both status line will change.
Not sure if this is the expected behaviour though. 😅

**Comment by vimpostor** [comment]
> It works, mostly. However, the embedded part is no longer responsive.

Try again, I just pushed another layer of workaround to make this work without issues.

**Comment by WilliamHsieh** [comment]
[This](https://github.com/andymass/vim-matchup#c3-display-matches-off-screen) feature will change the statusline to the offscreen match, it works normally on the original statusline, but not the embedded part. I guess I will disable the `g:matchup_matchparen_offscreen` feature for now and hope someday neovim is getting a patch to deal with the problem. Thanks again for the great plugin!

**Comment by vimpostor** [comment]
I think it might be a vim bug. Using `au OptionSet * echom expand('<amatch>')` we can see that [the line setting the statusline in vim-matchup](https://github.com/andymass/vim-matchup/blob/3fa1b2283e957784922fe891de361a2342b90bca/autoload/matchup/matchparen.vim#L582) generates the output `equalprg` instead of the expected `statusline`.
This requires further investigation.

**Comment by WilliamHsieh** [comment]
It works! This plugin indeed needs a bunch of workarounds, but in the end, I'm very happy with how it turns out. Thank's for your help!

**Comment by j2501987804** [comment]
> 通常它是用 完成的，但默认情况下这个插件已经这样做了。`set laststatus=0`
> 
> 为了重现，我需要更多信息。你能提供你的配置文件吗？

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	"nvim-lua/plenary.nvim",
	"kyazdani42/nvim-web-devicons",
	{
		"rebelot/kanagawa.nvim",
		config = function()
			vim.cmd("colorscheme kanagawa")
		end,
	},
	{
		"nvim-lualine/lualine.nvim",
		opts = {
			options = {
				component_separators = { left = "", right = "" },
				section_separators = { left = "", right = "" },
				-- disabled_filetypes = { "alpha", "NvimTree" },
			},
		},
	},
	"vimpostor/vim-tpipeline",
})

**Comment by j2501987804** [comment]
> 通常它是用 完成的，但默认情况下这个插件已经这样做了。`set laststatus=0`
> 
> 为了重现，我需要更多信息。你能提供你的配置文件吗？



> Usually it is done with `set laststatus=0`, but this plugin already does this by default.
> 
> In order to reproduce, I need more info. Can you provide your config file?

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	"nvim-lua/plenary.nvim",
	"kyazdani42/nvim-web-devicons",
	{
		"rebelot/kanagawa.nvim",
		config = function()
			vim.cmd("colorscheme kanagawa")
		end,
	},
	{
		"nvim-lualine/lualine.nvim",
		opts = {
			options = {
				component_separators = { left = "", right = "" },
				section_separators = { left = "", right = "" },
				-- disabled_filetypes = { "alpha", "NvimTree" },
			},
		},
	},
	"vimpostor/vim-tpipeline",
})
