### ISSUE TITLE
Broken in neovim nightly

### ISSUE THREAD

**Issue by jrnxf** [vimpostor/vim-tpipeline#46]
### Describe the bug

Title says it all - I can't seem to get this to work at all. I'm running nightly neovim and haven't had any luck. By any chance would you mind taking a peek at my config and helping me diagnose what might be the problem? I'm curious if it has something to do with using lazy as my package manager, but it's hard to debug when I can't get anything to even happen.

### To reproduce

If you clone `git@github.com:jrnxf/dot.git` and check out the `tpipeline` branch, you should be able to replicate

Of course you'll want to use my tmux and neovim configs. If you open up neovim with my config it should load everything on start. It might throw some errors but just exit out once and open it back up and you should be good to go.

### Terminal emulator

iterm2

**Comment by vimpostor** [comment]
> Of course you'll want to use my tmux and neovim configs.

Usually I'd prefer a more minimal reproducible example than "this entire config".

> I can't seem to get this to work at all.

Looks like your config works with neovim 0.8.3 but not with nightly. Bisecting neovim confirms that either [24488169564c39a506c235bf6a33b8e23a8cb528](https://github.com/neovim/neovim/commit/24488169564c39a506c235bf6a33b8e23a8cb528) or [43e8ec92de9e0850e7d202cb7ff9051bc408447e](https://github.com/neovim/neovim/commit/43e8ec92de9e0850e7d202cb7ff9051bc408447e) (can't test one of those commits, because it is broken) introduced a regression, where neovim causes the asynchronous background job to segfault. Both of these commits come from https://github.com/neovim/neovim/pull/18375 and looking at the references at the end of that thread, that PR introduced a lot of other regressions, sigh...

Some of the regressions are very similar to this bug: https://github.com/neovim/neovim/issues/21771

I will have to see how to fix this properly, but it probably requires upstream work.

**Comment by bfredl** [comment]
> Some of the regressions are very similar to this bug: https://github.com/neovim/neovim/issues/21771

Curious about this. what more state do you rely on being synchronized, apart from cwd as in the linked issue?

**Comment by vimpostor** [comment]
> what more state do you rely on being synchronized?

Not much, I think only the environment being preserved (tmux needs the `$TMUX` variable).

If I replace my generic `jobstart()` with a hardcoded:
```vimscript
let s:job = jobstart(command, #{on_stdout: {a,b,c -> append(line('.'),b)}, on_exit: {a,b,c -> append(line('.'), b)}})
```

Then I can see that the job exits unexpectedly with code `143`... I still need to investigate why, there is nothing printed on stderr.

Also I can't reproduce it if I do that `jobstart()` in isolation. Maybe it's a race condition somewhere, because I immediately start writing to stdin of that job.

**Comment by vimpostor** [comment]
@bfredl It seems that your patch broke detection of whether neovim runs in a GUI or in the TUI.

From the help page `:h v:event`:
```
			chan		|channel-id| or 0 for "internal".
```

However, after your patch this is no longer true. You can test it out with:
```vim
nvim --clean -Nu <(cat<<EOF
au UIEnter * echom v:event['chan']
EOF
```

Before your patch this correctly displayed **0** (as per documentation). After your patch it returns **1** instead.

What is the recommended way to detect TUI neovim (as opposed to neovim started in a GUI) now?

**Comment by bfredl** [comment]
For the moment, I think the simplest way might be `nvim_list_uis()[0].ext_termcolors` which is true for a terminal. (though potentially there could be multiple UI:s attached, some of which are TUI:s)
