### ISSUE TITLE
Tmux statusline updates have a huge delay

### ISSUE THREAD

**Issue by Nimmidev** [vimpostor/vim-tpipeline#50]
### Describe the bug

If the cursor is moved in neovim (or any other action is executed that changes the statusline content) the tmux statusline needs approximately 5 seconds until the content is updated. 

If two changes happen right after another (like moving the cursor twice `jj`) the tmux statusline updates immediately to the previous state but again takes 5 seconds to receive the last (current) state.

Example on [asciinema](https://asciinema.org/a/mRFiAkqVl13JXd9Awa1GUsdrK).

### To reproduce

With the following config (using `lazy.nvim` in neovim `v0.8.3`:
```
    {
        "nvim-lualine/lualine.nvim",
        lazy = false,
        opts = {
            options = {
                theme = "OceanicNext"
            }
        },
        setup = true
    },
    {
        lazy = false,
        "vimpostor/vim-tpipeline"
    }
```
With the following in tmux config:
```
set -g status-style bg=default
set -g status-left-length 90
set -g status-right-length 90
set -g status-justify absolute-centre
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -g focus-events on
```

1. Open neovim
2. Move cursor (or do any other action that changes the statusline)

### Expected behavior

Any changes are reflected immediately in the tmux statusline.

### Terminal emulator

alacritty 0.11.0 (8dbaa0bb)

### Debug output

```JSON
{'right': ['#[fg=,bg=]#[fg=#ffffff,bg=#343d46] utf-8 #[fg=#ffffff,bg=#343d46]  #[fg=#6d8086,bg=#343d46] #[fg=#ffffff,bg=#343d46] tmux #[fg=#65737e,bg=#343d46]#[fg=#ffffff,bg=#65737e] 14% #[fg=#6699cc,bg=#65737e]#[fg=#ffffff,bg=#6699cc,bold]  20:1  '], 'native_str': ' COMMAND   master  +8 ~1  tmux.conf utf-8     tmux  14%   20:1  ', 'version_info': '{   api_compatible = 0,   api_level = 10,   api_prerelease = false,   major = 0,   minor = 8,   patch = 3,   prerelease = false }', 'tmux': 'tmux 3.3a', 'left': ['#[fg=,bg=]#[fg=#ffffff,bg=#6699cc,bold] COMMAND #[fg=#6699cc,bg=#65737e,nobold]#[fg=#ffffff,bg=#65737e]  master #[fg=#99c794,bg=#65737e] +8 #[fg=#6699cc,bg=#65737e]~1 #[fg=#65737e,bg=#343d46]#[fg=#ffffff,bg=#343d46] tmux.conf #[fg=#ffffff,bg=#343d46]'], 'plugin_version': '1.0', 'native_highlights': [{'group': 'lualine_a_normal', 'start': 0}, {'group': 'lualine_transitional_lualine_a_normal_to_lualine_b_normal', 'start': 9}, {'group': 'lualine_b_normal', 'start': 12}, {'group': 'lualine_b_diff_added_command', 'start': 27}, {'group': 'lualine_b_diff_modified_command', 'start': 31}, {'group': 'lualine_transitional_lualine_b_diff_modified_command_to_lualine_c_normal', 'start': 34}, {'group': 'lualine_c_normal', 'start': 37}, {'group': 'lualine_c_normal', 'start': 48}, {'group': 'lualine_c_normal', 'start': 165}, {'group': 'lualine_c_normal', 'start': 175}, {'group': 'lualine_x_filetype_DevIconDefault_command', 'start': 183}, {'group': 'lualine_c_normal', 'start': 187}, {'group': 'lualine_transitional_lualine_b_normal_to_lualine_c_normal', 'start': 193}, {'group':'lualine_b_normal', 'start': 196}, {'group': 'lualine_transitional_lualine_a_normal_to_lualine_b_normal', 'start': 201}, {'group': 'lualine_a_normal', 'start': 204}], 'os': 'Linux', 'brand': 'neovim'}
```

**Comment by vimpostor** [comment]
Thanks for the bug report. Looks like the statusline is lagging behind exactly one iteration, I am not sure how that is even possible.
What statusline plugin do you use?

Here is a wild guess: Try loading and initializing tpipeline **after** your statusline plugin initializes (not the other way around).

I only ask to try this, because I know that some statusline plugins use a cursed custom hack to update the statusline instead of doing it in the vim-idiomatic way and in that case the order of `autocmd` could actually make a difference.

One of these statuslines is lualine, which for whatever fucked up reason refreshes the statusline based on a timer: https://github.com/nvim-lualine/lualine.nvim/pull/736
This has caused some problems in the past already (see #32) and it looks like unfortunately lualine seems to be pretty popular with neovim users.

If you are already initializing tpipeline last in `lazy.nvim`, I will need your entire config to reproduce this.

**Comment by Nimmidev** [comment]
Your guess was spot on. I am using lualine and the loading order does cause the issue. 

I have disabled auto loading for the plugin and manually loaded it via `:Lazy load vim-tpipeline` and the statusline worked as expected. Unfortunately neither adding lualine as a dependency to `vim-tpipeline` nor setting the loading priority changed anything. I will try a few more things and report back if i get it working somehow.

Thanks

**Comment by vimpostor** [comment]
> If lualine is the offender here, i have no problem switching tbh. I was just setting it up.

lualine is very likely to be the offender here (again). However, we can work around whatever bullshit they are doing in lualine.

Can you confirm that doing `:au OptionSet statusline call tpipeline#update()` fixes the problem? Then I can commit a workaround tomorrow.

**Comment by Nimmidev** [comment]
Yes, i can confirm that it work as intended using the workaround.

Will this have an impact on performance compared to other statuslines? If so i rather change my statusline,

Thanks, for your help and your work on this plugin. Its really nice having more screen space available.

**Comment by vimpostor** [comment]
> Will this have an impact on performance compared to other statuslines? If so i rather change my statusline,

The timer-based update of lualine does not follow the vim-idiomatic way of using `set statusline=%!MyStatusLine()`, where `MyStatusline()` is a function indirection that evaluates to the statusline. What lualine does instead, is reset the `statusline` variable to the evaluated final statusline value everytime anything happens that could change the statusline.

Now I haven't measured or profiled whether this will cause any significant performance issues (it likely doesn't have a large performance impact, but in any case it definitely is slower than just having a static `statusline` value and letting vim call into your statusline function).

The real problem is however not performance, but the fact that the timer-based statusline of lualine is a total hack and may cause other issues. You can browse the lualine issues to find several of those, e.g. https://github.com/nvim-lualine/lualine.nvim/issues/298 and many more.

**Comment by Nimmidev** [comment]
I see. Thanks for the detailed explanation.

**Comment by b0o** [comment]
Just wanted to share my own workaround to Lualine's bad behavior - monkey patch it to prevent Lualine from actually setting the `statusline` option. Might break if Lualine updates their internal code, but it seems to work great for now (this should come after you do `lualine.setup`):
```lua
local lualine_nvim_opts = require 'lualine.utils.nvim_opts'
local base_set = lualine_nvim_opts.set

lualine_nvim_opts.set = function(name, val, scope)
  if vim.env.TMUX ~= nil and name == 'statusline' then
    if scope and scope.window == vim.api.nvim_get_current_win() then
      vim.g.tpipeline_statusline = val
      vim.cmd 'silent! call tpipeline#update()'
    end
    return
  end
  return base_set(name, val, scope)
end
```
