### ISSUE TITLE
2 statuslines

### ISSUE THREAD

**Issue by 7ijme** [vimpostor/vim-tpipeline#53]
### Describe the bug

Yeah i don't know why but this happens
![image](https://user-images.githubusercontent.com/68817281/233456301-2f72ba8a-8da2-49f3-a6d6-95f52b245cca.png)

this is my lualine config
```lua
require("lualine").setup({
	options = {
		theme = "onedark",
	},
	sections = {
		lualine_a = { "mode" },
		lualine_b = { "branch", "diff", "diagnostics" },
		lualine_c = { "filename" },
		lualine_x = { "filetype" },
		lualine_y = { "location", "progress" },
		lualine_z = { "os.date('!%H:%M:%S', os.time()+get_timezone())" },
	},
})
```

### To reproduce

I just installed this and have lualine configured

### Expected behavior

Just 1 statusline

### Terminal emulator

Windows Terminal > wsl

### Debug output

```JSON
{'right': ['#[fg=,bg=]#[fg=#51a0cf,bg=#31353f] #[fg=#abb2bf,bg=#31353f] lua #[fg=#3b3f4c,bg=#31353f]#[fg=#abb2bf,bg=#3b3f4c] 120:1
#[fg=#abb2bf,bg=#3b3f4c] Bot #[fg=#e5c07b,bg=#3b3f4c]#[fg=#282c34,bg=#e5c07b,bold] 20:35:23 '], 'native_str': ' COMMAND   master 
 all.lua                                                                          lua  120:1   Bot  20:35:23 ', 'version_info': '{
   api_compatible = 0,   api_level = 11,   api_prerelease = false,   major = 0,   minor = 9,   patch = 0,   prerelease = false }', 'tm
ux': 'tmux 3.2a', 'left': ['#[fg=,bg=]#[fg=#282c34,bg=#e5c07b,bold] COMMAND #[fg=#e5c07b,bg=#3b3f4c,nobold]#[fg=#abb2bf,bg=#3b3f4c] 
 master #[fg=#3b3f4c,bg=#31353f]#[fg=#abb2bf,bg=#31353f] all.lua #[fg=#abb2bf,bg=#31353f]'], 'plugin_version': '1.0', 'native_highlig
hts': [{'group': 'lualine_a_command', 'start': 0}, {'group': 'lualine_transitional_lualine_a_command_to_lualine_b_normal', 'start': 9}
, {'group': 'lualine_b_normal', 'start': 12}, {'group': 'lualine_transitional_lualine_b_normal_to_lualine_c_normal', 'start': 24}, {'g
roup': 'lualine_c_normal', 'start': 27}, {'group': 'lualine_c_normal', 'start': 36}, {'group': 'lualine_x_filetype_DevIconLua_command'
, 'start': 107}, {'group': 'lualine_c_normal', 'start': 111}, {'group': 'lualine_transitional_lualine_b_normal_to_lualine_c_normal', '
start': 116}, {'group': 'lualine_b_normal', 'start': 119}, {'group': 'lualine_b_normal', 'start': 130}, {'group': 'lualine_transitiona
l_lualine_a_command_to_lualine_b_normal', 'start': 135}, {'group': 'lualine_a_command', 'start': 138}], 'os': 'Linux', 'brand': 'neovi
m'}
```

**Comment by vimpostor** [comment]
You can blame lualine for this, they are unconditionally setting `laststatus=2`, unless their useless globalstatus option is enabled: https://github.com/nvim-lualine/lualine.nvim/blob/84ffb80e452d95e2c46fa29a98ea11a240f7843e/lua/lualine.lua#L521

This is not only absolutely ridiculous, the entire lualine `globalstatus` option is a clown fiesta in and of itself, because it just replicates the `laststatus` option without adding any benefit (also read https://github.com/vimpostor/vim-tpipeline/issues/24#issuecomment-1106482005).

As a workaround for now you can put `au VimEnter * set laststatus=0` in your config to overwrite lualine's ridiculous behaviour.

But let me check if I can add a workaround from this plugin side so that it works without any user config...

In general though, I don't recommend using lualine, the maintainer has repeatedly shown being incompetent and unaware of following basic vim idiomatic patterns (see also https://github.com/vimpostor/vim-tpipeline/issues/51#issuecomment-1455229472 or https://github.com/vimpostor/vim-tpipeline/issues/50#issuecomment-1445504980 or grep the git log for the kind of workarounds that lualine needs)

**Comment by jackplus-xyz** [comment]
I ran into this issue too, here's my solution when using LazyVim.

## Tried but didn't work
```lua
-- ~/.config/nvim/lua/config/autocmds.lua
vim.api.nvim_create_autocmd("VimEnter", {
  callback = function()
    vim.opt.laststatus = 0
  end,
})
```

```lua
-- ~/.config/nvim/lua/config/options.lua
local opt = vim.opt
opt.laststatus = 0
```

## What works for me
```lua
-- ~/.config/nvim/lua/plugins/ui.lua
return  {
    "nvim-lualine/lualine.nvim",
    config = function(_, opts)
      require("lualine").setup(opts)
      vim.opt.laststatus = 0
    end,
  }
 ```

**Comment by dzirtusss** [comment]
For some reason none of the above (autocmd, init option, simple callback, etc) worked for me and there were 2 lines always.

The following adjustment always works:
```lua
config = function()
  require('lualine').setup({
    .......
  })

  if os.getenv('TMUX') then
    vim.defer_fn(function() vim.o.laststatus=0 end, 0)
  end
end
```
Plus tmux check, so works with or w/o tmux.

**Comment by vimpostor** [comment]
> For some reason none of the above (autocmd, init option, simple callback, etc) worked for me

You need to make sure that the autocmd runs after lualine's own autocmds (which create the problem in the first place). Furthermore, lazy.nvim's lazy loading may interfere even further, use a proper plugin manager. This plugin already uses Vim's native autoload mechanism for lazy loading.

**Comment by hashem78** [comment]
> For some reason none of the above (autocmd, init option, simple callback, etc) worked for me and there were 2 lines always.
> 
> The following adjustment always works:
> 
> ```lua
> config = function()
>   require('lualine').setup({
>     .......
>   })
> 
>   if os.getenv('TMUX') then
>     vim.defer_fn(function() vim.o.laststatus=0 end, 0)
>   end
> end
> ```
> 
> Plus tmux check, so works with or w/o tmux.

This worked for me, lualine is such a bitch to work with

**Comment by dzirtusss** [comment]
@hashem78 actually above solution is not a proper one ^^^ because the problem is not only lualine, but (in my case) a lualine+tpipeline+lazy.nvim combo. Actually, to all work correctly, one should ensure following sequence of events:
1. lualine is loaded first
2. lualine have cycles in interpreter to run its lua code and setup everything
3. tpipeline is initialized **after p1 AND p2**
4. possibly do p1-3 before `UIEnter` to avoid blinking

To test if everything is correctly initialized do `:autocmd ModeChanged`. Tpipeline hooks need to be after Lualine hooks. If they are the opposite, all works weirdly.

So the problem is how to ensure this with your package manager (I can say only about lazy.nvim).

Below is the config I use lately:
```lua
local function init()
  vim.g.tpipeline_autoembed = 0
  vim.fn.jobstart('~/bin/mytmuxstatusline', { detach = true })

  -- disable statusline in horizontal splits
  -- https://github.com/vimpostor/vim-tpipeline/issues/19
  vim.g.tpipeline_clearstl = 1

  -- fix lualine+tpipeline+lazy combo
  vim.defer_fn(function()
    local autocmds = vim.api.nvim_get_autocmds({ event = "ModeChanged" })
    if autocmds[#autocmds].group_name == 'tpipeline' then return end

    vim.api.nvim_del_augroup_by_name('tpipeline')
    vim.g.tpipeline_statusline = '' -- because tpipeline_clearstl=1
    vim.call('tpipeline#build_hooks')
  end, 0)
end

return {
  {
    'vimpostor/vim-tpipeline',
    init = init,
    dependencies = 'nvim-lualine/lualine.nvim',
  }
}
```

1. it ensures p1 via `dependencies`
2. it ensures p2 via `defer_fn`
3. it fixes `ModeChanged` hooks order (in a hacky way, but 🤷‍♂️ works for me and simple)

That's best way I have come so far.

**Alternative way** for lazy.nvim is to do:
```lua
{ 'vimpostor/vim-tpipeline', event = 'VeryLazy' }
```
Which just forces to load tpipeline after all plugins are loaded and `VimEnter`. But it creates some flickering on startup (p4) because it is after `VimEnter`, so it draws one UI, and then quickly another UI, which results in brief blink.

I don't say that those are "idiomatically correct" fixes, and maybe they can be improved, but the problem is exactly what I said in the begining, so any other solution that addresses it will also work.

Feel free to use.

**Comment by aaron-weisberg-qz** [comment]
I've noticed when re-entering neovim or changing colorscheme with lualine and lazyvim, I'd get the double line. This has worked really well for me though:
```lua
  {
    "nvim-lualine/lualine.nvim",
    -- https://github.com/vimpostor/vim-tpipeline/issues/53
    config = function(_, opts)
      require("lualine").setup(opts)

      if vim.env.TMUX then
        vim.api.nvim_create_autocmd({ "FocusGained", "ColorScheme" }, {
          callback = function()
            vim.defer_fn(function()
              vim.opt.laststatus = 0
            end, 100)
          end,
        })

        vim.o.laststatus = 0
      end
    end,
    opts = {

...
...

**Comment by vimlinuz** [comment]
I don't know why but WinResize worked for me
```nix
      {
        event = [
          "WinResized"
        ];
        pattern = "*";
        command = "lua
        if vim.env.TMUX then
          vim.opt.laststatus = 0
        end
          ";
      }
```
