### ISSUE TITLE
Annoying refresh of status  

### ISSUE THREAD

**Issue by tami5** [vimpostor/vim-tpipeline#6]
Hey @vimpostor awesome work, I like it a lot. 

I have few issues to make this my daily driver and I hope someone can help me out with

#### Preview:
![statuslinetmux](https://user-images.githubusercontent.com/65782666/108560062-3e2f7a00-730d-11eb-9b41-746e2f663f1f.gif)

- Keeping the middle section centered, not influenced by vim, the issue here that when I switch the positioning of the center changes which is very annoying refresh.
- The colors mismatch , I'm looking into a way to fix that now.

Thanks @vimpostor

**Comment by vimpostor** [comment]
I agree, I stumbled upon this problem before and I agree that this can trigger OCD. The best way to solve this is tbh if tmux implemented something upstream to center the window list absolutely. This is probably something close to a one-liner to implement in tmux, but it seems like nothing has been done to achieve this yet: https://superuser.com/a/1016734

There is also the possibility to do a workaround from our side by padding the string we output to an absolute length. This way the broken relative centering in tmux is automatically equivalent to absolute centering.
We can do this in two ways:
- Pad the string from the tmux config side: When you search in the tmux manual for 'pad', there seems to be a #{p:arg} option to pad arg. But from my quick experiments it doesn't seem to work with commands: set -g status-left '#{p30:#(cat #{socket_path}-\#{session_id}-vimbridge)}' I tried some other combinations but nothing worked with commands.
- Pad the string from within the plugin side. This is very cursed, as it would involve parsing the tmux statusline syntax from our side. Well you don't really need to properly parse it, as you can just throw away stuff like '#[fg=#cfcfcf,bg=#212121]' instead of parsing it but there are a few edgecases that will make this a pain to implement and add to much overhead.

Overall I think working around this from our side is probably not the best way forward as this is a problem arising from tmux's side.

If you too don't find a quick way to make this work with the #{p:arg} tmux option to pad this, I will probably just go fix this from the tmux side myself and implement absolute centering.

**Comment by vimpostor** [comment]
As for your second problem, I don't really understand what you mean. What colors are not matching exactly? They should all match perfectly with what you have configured in vim as colorscheme. From your screenshot I can't really tell what colors are not matching. Maybe you are missing true color support in tmux or your terminal?

________________________________
Von: tami5 <notifications@github.com>
Gesendet: Freitag, 19. Februar 2021 21:54:28
An: vimpostor/vim-tpipeline
Cc: Groß, Magnus; Mention
Betreff: [vimpostor/vim-tpipeline] Annoying refresh of status (#6)


Hey @vimpostor<https://github.com/vimpostor> awesome work, I like it a lot.

I have few issues to make this my daily driver and I hope someone can help me out with

Preview:

[statuslinetmux]<https://user-images.githubusercontent.com/65782666/108560062-3e2f7a00-730d-11eb-9b41-746e2f663f1f.gif>

  *   Keeping the middle section centered, not influenced by vim, the issue here that when I switch the positioning of the center changes which is very annoying refresh.
  *   The colors mismatch , I'm looking into a way to fix that now.

Thanks @vimpostor<https://github.com/vimpostor>

**Comment by tami5** [comment]
> As for your second problem, I don't really understand what you mean. What colors are not matching exactly? They should all match perfectly with what you have configured in vim as colorscheme. From your screenshot I can't really tell what colors are not matching. Maybe you are missing true color support in tmux or your terminal?

Oh yah for that I needed to define fill property to make colors match.


I agree I think a tmp solution for that is through definite padding that doesn't get influenced by statusline  section value

**Comment by vimpostor** [comment]
Hi,

I have now implemented better centering in upstream tmux itself.
You can activate the new perfect centering with:
```bash
set -g status-justify absolute-centre
```

This will fix the weird flickering of the window list.

The new centering will be available with the upcoming tmux release `3.2`.
Alternatively you can compile the master branch yourself to get the feature today.
