### ISSUE TITLE
Double Statusline in Neovim

### ISSUE THREAD

**Issue by avih7531** [vimpostor/vim-tpipeline#63]
### Describe the bug

I'm getting both my native nvim statusline (sttusline) and then  a recreation of it via vim-tpipeline which works perfectly, but the nvim status line stays.

### To reproduce

Enter a new tmux session and go into nvim. See below for my config files

.tmux.conf
```
unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g focus-events on
set -g status-style bg=default
set -g status-left-length 90
set -g status-right-length 90
set -g status-justify centre

set -sg escape-time 0

set -g default-terminal "xterm-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"
run '~/.tmux/plugins/tpm/tpm'
 ```

sttusline setup via Lazy
```
return {
	"sontungexpt/sttusline",
	dependencies = {
		"nvim-tree/nvim-web-devicons",
	},
	event = { "BufEnter" },

	config = function()
		local mode = require("sttusline.components.mode")
		mode.set_config({
			modes = {
				["no"] = { "DELETE", "STTUSLINE_DELETE_MODE" },
			},
			mode_colors = {
				["STTUSLINE_VISUAL_MODE"] = { fg = "#cf9e40" },
				["STTUSLINE_DELETE_MODE"] = { fg = "#df2020" },
				["STTUSLINE_INSERT_MODE"] = { fg = "#a4aa4e" },
			},
		})
		require("sttusline").setup({
			statusline_color = "#242933",
			laststatus = 3,
			disabled = {
				filetypes = {
					"neo-tree",
					"lazy",
					"No File",
					"Mason",
				},
				buftypes = {
					"terminal",
				},
			},
			components = {
				"mode",
				"filename",
				"git-branch",
				"git-diff",
				"%=",
				"diagnostics",
				"lsps-formatters",
				"copilot",
				"indent",
				"encoding",
				"pos-cursor",
				"pos-cursor-progress",
			},
		})
		vim.cmd("set noshowmode")
	end,
}
```

### Expected behavior

That there would only be one status line which integrates neovim + tmux

### Terminal emulator

Alacritty

### Debug output

```Text
I did this in an empty buffer:

{'native_str': 'COMMAND  No File                                                                                                                                    NO LSP, FORMATTER 
```

**Comment by avih7531** [comment]
I know the screenshot contradicts what I said, but it's because Hyprland treats screenshots as focusing on a different window. When in tmux and in the nvim pane the tpipline is the normal neovim one with the tmux additions:
![20240329_00h31m38s_grim](https://github.com/vimpostor/vim-tpipeline/assets/45245854/6509f325-8c39-4b41-a89f-64f8c83c7095)

**Comment by avih7531** [comment]
Update:
It is 100% a sttusline problem -- I just tried it with lualine and it was seamless. 

Could this please be patched for sttusline in the future? Would love to help but have no idea where to start.

Thanks!

**Comment by vimpostor** [comment]
> Could this please be patched for sttusline in the future?

Yes, but why are you opening the issue here and not in sttusline?

You can use `:verbose set laststatus` to see that sttusline is overwriting the `laststatus` option without any reason whatsoever, which causes the statusline to be displayed in vim again (hence you seeing two statuslines).

The reason is [this line in sttusline](https://github.com/sontungexpt/sttusline/blob/133bb40d249e0167c89bb352ff8442b821fb07e9/lua/sttusline/config.lua#L42).

This is probably the most idiotic code I have ever read in my life. You can grep sttusline for all usages of `laststatus`. They are completely out of their mind and are literally just exposing an internal `laststatus` option for absolutely no fucking reason and then just set the vim `laststatus` option to the value of their own `laststatus` option, WTF why in the name of Jesus Christ would you do something unhinged like this, any sane user would just set vim's `laststatus` directly instead of using your fucking useless option.
All you are accomplishing is breaking unrelated configs, because you [hardcode laststatus to 3 for people that don't set it](https://github.com/sontungexpt/sttusline/blob/133bb40d249e0167c89bb352ff8442b821fb07e9/lua/sttusline/config.lua#L8), even if they set a different value in their `vimrc`.

> It is 100% a sttusline problem -- I just tried it with lualine and it was seamless.

[Lualine did the same stupid shit](https://github.com/vimpostor/vim-tpipeline/issues/24#issuecomment-1106482005) and it is clear that the author of sttusline probably copied that practice from there. Unfortunately [I added a workaround just for lualine](https://github.com/vimpostor/vim-tpipeline/commit/34a38d938f6e6145dea6307f7706480070ddf5c4), which I now regret.

These statuslines should fix their shit upstream instead of letting other plugins add workarounds, because apparently all neovim plugin developers are incapable of using any vim-idiomatic APIs correctly.

For a quick hacky fix, you can use [the workaround from this comment](https://github.com/vimpostor/vim-tpipeline/issues/53#issuecomment-1516938292) in the meantime. But ultimately statusline plugins should stop hardcoding `laststatus` for absolutely no fucking reason.
